
---
title: "Upset plot s.fitti"
author: "Kate Stankiewicz"
date: "3/4/2021"
output: html_document
---



```{r}
# load the libraries
library(UpSetR)
library(dplyr)
```

```{r}
#set the working directory
setwd("~/sym_ortho_analysis")

#read in the file for the gene counts generated by OrthoFinder2
gene_counts <- read.table("Orthogroups.GeneCount.tsv", header = T, row.names = 1)
```

```{r}
#remove the Total column
no_total <- subset(gene_counts, select = -c(Total))
```

```{r}
#rename each column to have the full species name
new_name <- no_total %>% rename(B.minutum = B.min, Cladocopium.C15 = C.C15, Cladocopium.C92 = C.C92, D.trenchii = D.tre, F.kawagutii = F.kaw, S.fitti = S.fit, S.linucheae = S.lin, S.microadriaticum = S.mic, S.natans = S.nat, S.necroappetens = S.nec, S.pilosum = S.pil, S.tridacnidorum = S.tri)
```

```{r}
#now lets make it binary (gene counts that are non zero (aka >=1) will be now be set to 1)
new_name[is.na(new_name)] <- as.integer(0)
new_name[new_name != 0] <- as.integer(1)
```

```{r}
#get the groups to highlight:
#all species
list_all <- colnames(new_name)
#symbiodinium only
sym_only <- grep('S.', list_all, ignore.case = F, value = T)

#now we can make an upset plot
upset(new_name, sets = c("B.minutum","Cladocopium.C15","Cladocopium.C92", "D.trenchii", "F.kawagutii", "S.fitti", "S.linucheae", "S.microadriaticum", "S.natans", "S.necroappetens", "S.pilosum", "S.tridacnidorum"), nsets = 12, sets.x.label = "Orthogroups per Species", mainbar.y.label = "Number of Orthogroups", keep.order = T, point.size = 3.5, text.scale = c(2.5, 1.5, 1.3, 1, 1.5, 1.2), order.by = "freq", number.angles = 15, nintersects = 40, query.legend = "bottom", queries = list(list(query = intersects, params = list(list_all), color = "coral", active = T, query.name="Symbiodiniaceae"), list(query = intersects, params = list(sym_only), color = "goldenrod", active = T, query.name="Symbiodinium")))
```

